/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include <string.h>

#include "UART.h"
#include "I2C.h"
#include "LCD.h"
#include "Systick.h"
#include "RTC.h"


char time_str[17];
char date_str[17];

int main(void)
{
    DS1307_Time_t rtc;

    /* -------- Init -------- */
    I2C1_GPIO_Init();
    I2C1_Init();
    I2C1_EN();

    LCD_Init();
    DS1307_Init();

    /* ---- SET TIME ONCE (then comment) ---- */
/*
    rtc.sec   = 0;
    rtc.min   = 27;
    rtc.hour  = 22;   // 24-hour format
    rtc.day   = 2;
    rtc.date  = 26;
    rtc.month = 12;
    rtc.year  = 25;
    DS1307_SetTime(&rtc);
*/

    while(1)
    {
        /* Read RTC */
        DS1307_GetTime(&rtc);

        /* Format time HH:MM:SS */
        sprintf(time_str, "TIME %02d:%02d:%02d",
                rtc.hour, rtc.min, rtc.sec);

        /* Format date DD/MM/YY */
        sprintf(date_str, "DATE %02d/%02d/%02d",
                rtc.date, rtc.month, rtc.year);

        /* Display */
        LCD_Command(Clear);

        LCD_Set_Cursor(0, 0);
        LCD_Send_Data(strlen(time_str), (uint8_t*)time_str);

        LCD_Set_Cursor(1, 0);
        LCD_Send_Data(strlen(date_str), (uint8_t*)date_str);

        systickDelayMs(1000);
    }
}




