/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include <string.h>
#include "UART.h"
#include "I2C.h"
#include "LCD.h"
#include "Systick.h"


char rx_buf[]="Hello World";
char time[]="Time(sec):";
char time_str[10];
int main(void)
{
	uint8_t time1 = 0;
	I2C1_GPIO_Init();
	I2C1_Init();
	I2C1_EN();
	LCD_Init();


	while(1)
	{
		LCD_Command(Clear);
		LCD_Set_Cursor(0, 0);
		LCD_Send_Data(strlen(rx_buf), (uint8_t*)rx_buf);
		LCD_Set_Cursor(1, 0);
		LCD_Send_Data(strlen(time), (uint8_t*)time);
		LCD_Set_Cursor(1, strlen(time)+1);
		// Convert the integer 'time' to a string
		  sprintf(time_str, "%d", time1);

		//Send the string (which now contains valid ASCII codes)
		 LCD_Send_Data(strlen(time_str), (uint8_t*)time_str);
		time1++;
		systickDelayMs(1000);

	}
}




